modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU GPLv3"
[[mods]]
modId = "katyouvotifier"
version = "${file.jarVersion}"
displayName = "Katyou Votifier"
authors = "MORIMORI0317 ,NuVotifier authors[Ichbinjoe, blakeman8192, Kramer, tuxed]"
description = '''
A mod that gets notified when votes are made for the server on toplists.
Forked NuVotifier and ported it to Forge
'''
